# Generated by Django 5.2 on 2025-05-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_created_at_customer_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='customer',
            name='service_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
